GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/68a5ea88d304eabfca566da0

###
DELETE http://localhost:3001/api/persons/68a4cb84c5ce906e450a0b22

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "martin",
    "number": "123-1234123123123531"
}

###
PUT http://localhost:3001/api/persons/68a5ea88d304eabfca566da0
Content-Type: application/json

{
    "name": "martin",
    "number": "923-12345"
}