GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/68ac9aa8eefeddd1f2f4e3ae

###
DELETE http://localhost:3001/api/persons/68ac9aa8eefeddd1f2f4e3ae

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Antonio Pujante",
    "number": "123-1234123"
}

###
PUT http://localhost:3001/api/persons/68ac9aa8eefeddd1f2f4e3ae
Content-Type: application/json

{
    "name": "Antonio Pujante",
    "number": "23-123456"
}